-- Generated by Home Manager.
-- See https://wezfurlong.org/wezterm/

local wezterm = require("wezterm")
local scheme = wezterm.get_builtin_color_schemes()["Catppuccin Mocha"]

local dump_scrollback_to_file = function(pane)
	local zones = pane:get_semantic_zones("Output")

	if #zones == 0 then
		return
	end

	local scrollback = pane:get_text_from_semantic_zone(zones[#zones])

	-- Create a temporary file to pass to vim
	local name = os.tmpname()
	local f = io.open(name, "w+")
	f:write(scrollback)
	f:flush()
	f:close()
	return name
end

wezterm.on("trigger-vim-with-scrollback", function(window, pane)
	local filename = dump_scrollback_to_file(pane)
	if not filename then
		return
	end
	-- Open a new window running fzf to fuzzy search scrollback
	window:perform_action(
		wezterm.action({
			SpawnCommandInNewWindow = {
				args = {
					"/run/current-system/sw/bin/fish",
					"-c",
					"nvim " .. filename .. "; rm -f " .. filename,
				},
				cwd = pane:get_current_working_dir(),
			},
		}),
		pane
	)
end)

return {
	check_for_updates = false,
	color_scheme = "Ayu Mirage",
	inactive_pane_hsb = {
		hue = 1.0,
		saturation = 1.0,
		brightness = 1.0,
	},
	-- default_prog = { '/bin/bash', '-l' },
	-- font = wezterm.font 'Ubuntu Mono derivative Powerline',
	-- font = wezterm.font 'UbuntuMono Nerd Font',
	font = wezterm.font("Mono Lisa"),
	font_size = 17.0,
	freetype_load_flags = "NO_HINTING",
	disable_default_key_bindings = true,
	keys = {
		-- Send "CTRL-A" to the terminal when pressing CTRL-A, CTRL-A
		-- { key = "a", mods = "LEADER|CTRL",  action=wezterm.action{SendString="\x01"}},
		{ key = "-", mods = "CMD", action = wezterm.action({ SplitVertical = { domain = "CurrentPaneDomain" } }) },
		{ key = "=", mods = "CMD", action = wezterm.action({ SplitHorizontal = { domain = "CurrentPaneDomain" } }) },
		{ key = "z", mods = "CMD", action = "TogglePaneZoomState" },
		{ key = "t", mods = "CMD", action = wezterm.action({ SpawnTab = "CurrentPaneDomain" }) },
		{ key = "h", mods = "CMD", action = wezterm.action({ ActivatePaneDirection = "Left" }) },
		{ key = "j", mods = "CMD", action = wezterm.action({ ActivatePaneDirection = "Down" }) },
		{ key = "k", mods = "CMD", action = wezterm.action({ ActivatePaneDirection = "Up" }) },
		{ key = "l", mods = "CMD", action = wezterm.action({ ActivatePaneDirection = "Right" }) },
		{ key = "H", mods = "CMD|SHIFT", action = wezterm.action({ AdjustPaneSize = { "Left", 5 } }) },
		{ key = "J", mods = "CMD|SHIFT", action = wezterm.action({ AdjustPaneSize = { "Down", 5 } }) },
		{ key = "K", mods = "CMD|SHIFT", action = wezterm.action({ AdjustPaneSize = { "Up", 5 } }) },
		{ key = "L", mods = "CMD|SHIFT", action = wezterm.action({ AdjustPaneSize = { "Right", 5 } }) },
		{ key = "1", mods = "CMD", action = wezterm.action({ ActivateTab = 0 }) },
		{ key = "2", mods = "CMD", action = wezterm.action({ ActivateTab = 1 }) },
		{ key = "3", mods = "CMD", action = wezterm.action({ ActivateTab = 2 }) },
		{ key = "4", mods = "CMD", action = wezterm.action({ ActivateTab = 3 }) },
		{ key = "5", mods = "CMD", action = wezterm.action({ ActivateTab = 4 }) },
		{ key = "6", mods = "CMD", action = wezterm.action({ ActivateTab = 5 }) },
		{ key = "7", mods = "CMD", action = wezterm.action({ ActivateTab = 6 }) },
		{ key = "8", mods = "CMD", action = wezterm.action({ ActivateTab = 7 }) },
		{ key = "9", mods = "CMD", action = wezterm.action({ ActivateTab = 8 }) },
		{ key = "W", mods = "CMD|SHIFT", action = wezterm.action({ CloseCurrentPane = { confirm = true } }) },

		{ key = "d", mods = "CMD|SHIFT", action = wezterm.action({ ScrollByPage = 1 }) },
		{ key = "u", mods = "CMD|SHIFT", action = wezterm.action({ ScrollByPage = -1 }) },

		{ key = "v", mods = "CMD", action = wezterm.action.PasteFrom("Clipboard") },
		{ key = "c", mods = "CMD", action = wezterm.action.CopyTo("Clipboard") },
		{ key = "p", mods = "CMD", action = "QuickSelect" },
		{ key = "[", mods = "CMD", action = "ActivateCopyMode" },
		{ key = "f", mods = "CMD", action = wezterm.action({ Search = { CaseInSensitiveString = "" } }) },

		{ key = "UpArrow", mods = "SHIFT", action = wezterm.action.ScrollToPrompt(-1) },
		{ key = "DownArrow", mods = "SHIFT", action = wezterm.action.ScrollToPrompt(1) },

		{
			key = "g",
			mods = "CMD|SHIFT",
			action = wezterm.action({ EmitEvent = "trigger-vim-with-scrollback" }),
		},
		{ key = "l", mods = "CMD|SHIFT", action = wezterm.action.ShowDebugOverlay },
	},
	mouse_bindings = {
		{
			event = { Down = { streak = 3, button = "Left" } },
			action = wezterm.action.SelectTextAtMouseCursor("SemanticZone"),
			mods = "NONE",
		},
	},
	set_environment_variables = {},

	use_fancy_tab_bar = true,
	hide_tab_bar_if_only_one_tab = true,

	colors = {
		tab_bar = {
			background = scheme.background,
			new_tab = { bg_color = "#2e3440", fg_color = scheme.ansi[8], intensity = "Bold" },
			new_tab_hover = { bg_color = scheme.ansi[1], fg_color = scheme.brights[8], intensity = "Bold" },
			-- format-tab-title
			-- active_tab = { bg_color = "#121212", fg_color = "#FCE8C3" },
			-- inactive_tab = { bg_color = scheme.background, fg_color = "#FCE8C3" },
			-- inactive_tab_hover = { bg_color = scheme.ansi[1], fg_color = "#FCE8C3" },
		},
	},

	launch_menu = {
		{ label = "bash", args = { "bash", "-l" } },
		{ label = "fish", args = { "fish", "-l" } },
	},

	enable_kitty_keyboard = true,
	enable_csi_u_key_encoding = false,

	scrollback_lines = 10000,
}
